DROP TABLE IF EXISTS Customer, Server;

CREATE TABLE Customer (
id SERIAL PRIMARY KEY,
name VARCHAR(50) NOT NULL UNIQUE,
BCH4 VARCHAR(4) NOT NULL UNIQUE
);

CREATE TABLE Server (
id SERIAL PRIMARY KEY,
Hostname VARCHAR(50) NOT NULL UNIQUE,
IP VARCHAR(15) NOT NULL UNIQUE,
TYPE VARCHAR(6) NOT NULL,
ID_CUSTOMER int
);

ALTER TABLE SERVER ADD FOREIGN KEY (ID_CUSTOMER) REFERENCES Customer(id);
